name: AI Task Automation

on:
  issues:
    types: [labeled]

jobs:
  ai-task:
    if: contains(github.event.label.name, 'ai-task')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Run AI Task Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        REPOSITORY: ${{ github.repository }}
      run: |
        uv run python .github/scripts/ai_task.py

    - name: Comment on issue
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          let comment = 'AI task processing completed.';
          
          try {
            if (fs.existsSync('ai_task_result.md')) {
              comment = fs.readFileSync('ai_task_result.md', 'utf8');
            }
          } catch (error) {
            console.log('No result file found, using default comment');
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
