name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Sync deps (with dev tools)
        run: uv sync --dev
      - name: Lint (ruff)
        run: uv run ruff check .
      - name: Format check (black)
        run: uv run black --check .
      - name: Type check (mypy)
        run: uv run mypy src
      - name: Tests
        run: uv run pytest -q
